DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  about TEXT DEFAULT NULL,
  fullname TEXT DEFAULT NULL,
  nickname CITEXT UNIQUE ,
  email CITEXT UNIQUE
);


CREATE TABLE IF NOT EXISTS forums (
  id SERIAL PRIMARY KEY,
  posts INTEGER DEFAULT 0,
  threads INTEGER DEFAULT 0,
  title TEXT,
  slug CITEXT UNIQUE NOT NULL,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE NOT NULL
);
