CREATE EXTENSION IF NOT EXISTS CITEXT;


CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  about TEXT DEFAULT NULL,
  fullname TEXT DEFAULT NULL,
  nickname CITEXT UNIQUE ,
  email CITEXT UNIQUE
);


CREATE TABLE IF NOT EXISTS forums (
  id SERIAL NOT NULL PRIMARY KEY,
  posts INTEGER DEFAULT 0,
  threads INTEGER DEFAULT 0,
  title TEXT,
  slug CITEXT UNIQUE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);


CREATE TABLE IF NOT EXISTS threads (
  id SERIAL NOT NULL PRIMARY KEY,
  message TEXT,
  created TIMESTAMPTZ DEFAULT NOW(),
  slug CITEXT UNIQUE,
  title TEXT,
  votes INTEGER DEFAULT 0,
  author_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  forum_id INTEGER REFERENCES forums(id) ON DELETE CASCADE NOT NULL
);


CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created TIMESTAMPTZ DEFAULT NOW(),
  forum_id INTEGER REFERENCES forums(id) ON DELETE CASCADE NOT NULL,
  is_edited BOOLEAN NOT NULL DEFAULT FALSE,
  message TEXT,
  parent INTEGER DEFAULT 0,
  thread_id INTEGER REFERENCES threads(id) ON DELETE CASCADE NOT NULL,
  root_id INTEGER,
  path INTEGER [] NOT NULL
);